### November 08, 2024
## dataxp

api@23f3b4b
The release notes include the following changes:

The error message thrown when a field key has multiple instances of the same stored constraint validator has been updated. Instead of stating "Field key 'new_field' has multiple instances of the constraint validator: 'foo'", the error message now states "Field key 'new_field' has multiple instances of the stored constraint validator: 'foo'". This change clarifies that the error is specific to stored constraint validators and not external constraint validators.

The code has been updated to check for duplicate stored constraint validators only, instead of checking for both stored and external constraint validators. The following code block has been modified:

```typescript
field.constraints?.forEach((constraint) => {
  if (constraint.type === BaseConstraintTypeEnum.Stored) {
    if (constraintSet.has(constraint.validator)) {
      throw new HandledBadRequestException(
        `Field key "${field.key}" has multiple instances of the stored constraint validator: "${constraint.validator}"`
      )
    } else {
      constraintSet.add(constraint.validator)
    }
  }
})
```

This change ensures that only stored constraint validators are checked for duplicates, and external constraint validators are not included in the duplicate check.